### ISSUE TITLE
Support MonadIO instead of IO.

### ISSUE THREAD

**Issue by seanparsons** [simonmar/async#16]
If MonadIO was available to use instead of IO it would be much easier to use with monad stacks that involve IO.

**Comment by robertmassaioli** [comment]
I would really appreciate this as it would help make working with Snap stacks easier:

http://stackoverflow.com/questions/24090772/embed-async-within-a-monad-implementing-monadio

And the problem is not lifting async commands into higher monads but rather letting monads other than IO be passed into async functions.

**Comment by maoe** [comment]
Passing a lifted action to `async` wouldn't be possible just with `MonadIO` because the lifted monad type `m` appears in a negative position of `async`. You could use [lifted-async](https://hackage.haskell.org/package/lifted-async) instead which involves [monad-control](https://hackage.haskell.org/package/monad-control) to address the issue.

Note that lifted-async rarely make sense if you are working with a monad transformer stack which has monadic state. See https://github.com/maoe/lifted-async/pull/7#issuecomment-67266657 for the details.
