### ISSUE TITLE
race somehow changes async exception semantics?

### ISSUE THREAD

**Issue by osa1** [simonmar/async#63]
Summary: `race a waitForever` works differently than just `a`.

I have this program:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}

import Control.Concurrent
import Control.Concurrent.Async
import Control.Concurrent.Chan
import Control.Concurrent.MVar
import Control.Exception
import Data.Functor
import System.Mem

doWork
    :: MVar () -- ^ Stop signal
    -> IO (Either () ())
doWork stop_ref =
    race (readMVar stop_ref `catch` \(e :: SomeException) -> print e)
         (threadDelay maxBound)

main :: IO ()
main = do
    var <- newEmptyMVar
    thr <- async (doWork var)
    performMajorGC
    wait thr >>= print
```

This program blocks forever. However, if I change doWork to this:

```haskell
doWork stop_ref =
    Right <$> (readMVar stop_ref `catch` \(e :: SomeException) -> print e)
```

It prints exception messages as expected.

Just as an experiment, I tried using this `race` function:

```haskell
race' left right =
  withAsync left $ \a ->
  withAsync right $ \b ->
  waitEither a b
```

but it still didn't print the expected messages.

I would expect this to hold: `forall a . race a waitForever == Left <$> a`. I think we should at least understand and explain this behavior in the documentation.

**Comment by ChristopherKing42** [comment]
`waitEither` says that if the first `Async` to finish raises an exceptions, it should re-raise that exception. So there is a bug somewhere.

**Comment by simonmar** [comment]
This is perhaps counterintuitive, but it's working as expected. The GC can't detect a deadlock because the main thread has a reference to both child threads, and one of the child threads is in `threadDelay`. The GC can't prove that `threadDelay` will never return, or that the main thread won't decide to `cancel` the `readMVar` thread at some point, so there's no verifiable deadlock here.

The thing to bear in mind is that `BlockedIndefinitelyOnMVar` is a debugging feature. We can't give a precise description of its semantics because it depends on very operational properties (like reachability) that can't be precisely described at the language level. So when `BlockedIndefinitely` exceptions are involved, some properties that we might expect to hold (like `race a waitForever == Left <$> a`) don't.

Is this bad? Arguably yes, but then having the runtime detect deadlocks is also tremendously useful. cc @ndmitchell

**Comment by simonmar** [comment]
@alaendle Think of it this way: `Async.wait a` will block forever if (1) `a` is blocked forever and (2) nothing can cancel the current thread. Inside a `race`, (2) becomes false because the `race` can cancel the `Async.wait`.

Using weak pointers to ThreadIds might be able to fix this. Maybe worth looking into.
