### ISSUE TITLE
Feature request: linkSpecific

### ISSUE THREAD

**Issue by skogsbaer** [simonmar/async#64]
The `link` function rethrows exception of an asycn in the current thread. Sometimes, it's useful to only rethrow certain exceptions. For example, canceling an asyn works by throwing an asynchronous exceptions and there are situations where this asynchronous exception should not be rethrown in the thread linked to the async. See #25.

More specifically, I propose the following new function

    -- | Rethrow only specific exceptions of the given @Async@ in the current thread.
    linkSpecific :: (SomeException -> Bool) -> Async a -> IO ()

The implementation of `linkSpecific` is a straightforward generalization of `link`. I all agree that such a function is useful, I can provide a pull request.

**Comment by ntc2** [comment]
Even better, make the default behavior of `link` to not propagate the exception used by `cancel`, and make `cancel` use a custom exception specific to `Control.Concurrent.Async`, instead of reusing `ThreadKilled`. [I've also suggested this on #25](https://github.com/simonmar/async/issues/25#issuecomment-348330204).

**Comment by simonmar** [comment]
I'm tempted to deprecate `link` and `link2`. I don't like them because they throw sync exceptions asynchronously, which breaks assumptions. Would anyone here object?

**Comment by ntc2** [comment]
@simonmar , my `link` use case is to make my program fail fast on any uncaught exceptions, instead of having them silently disappear when generated by non-`wait`ed child threads. For example, I often have a worker thread that consumes input from a `Chan` indefinitely, and I don't `wait` for such a thread. If the worker thread silently fails with an uncaught exception, other threads keep sending input to its no-longer-monitored `Chan`, which is a confusing failure mode. I don't see how to "fail fast" here without using something essentially like `link`.

Instead of directly `link`ing the children to their parents, I could use a separate "fail fast" watchdog thread with a `Chan` that I sent all my `Async`s to at creation time, and that fail fast thread could monitor for the failures. This would eliminate the "`link` throws sync exceptions asynchronously" concern by scoping it to the watch dog thread. But I imagine the fail fast thread would still do this monitoring via something like `link` (i.e. forking a separate monitor thread for each monitored `Async`), since e.g. using `waitAny` in a loop in the watch dog thread itself would suffer from the O(n^2) STM transaction problem you describe in your (great!) concurrent Haskell book.

Thoughts?

**Comment by simonmar** [comment]
Done.
