### ISSUE TITLE
Explain link/link2 and forkRepeat

### ISSUE THREAD

**Issue by ndmitchell** [simonmar/async#68]
Reading through the source to async, it makes a lot of sense and I can follow many of the details, apart from `link` and `link2`. That might be my lack of understanding, might be a bug, or might be something that can be improved, or added as comments. My questions are:

* Why doesn't `link` use `waitCatch`, which does the `BlockedIndefinitelyOnSTM` retry semantics.
* If `link` used `waitCatch` is `forkRepeat` needed?
* Is there any risk that `throwTo` raises an exception? If so, won't that trigger an infinite loop?
* `link2` uses `forkRepeat`, and `waitCatchEither` doesn't retry on `BlockedIndefinitelyOnSTM`. Should `waitCatchEither` retry? If so, should `forkRepeat` still live?
* Shouldn't almost everything retry on `BlockedIndefinitelyOnSTM`?

FWIW, I'm increasingly unconvinced GHC's deadlock detection is correct... It fundamentally assumes that throwing an exception won't recover a thread, which isn't true. It seems to be causing quite a few weird corner cases (there was on in Shake too).

**Comment by simonmar** [comment]
I actually don't like `link`, I'm not sure we should have it at all. It turns synchronous exceptions into asynchronous exceptions, which violates assumptions we usually expect to hold.  I personally have never used it. I've just been dragging my feet in deprecating it, in case there's some legitimate use case that I'm overlooking. If you have a use for it, I'd be interested to see whether the use case might be expressed in some other way.

But still, to answer the questions:
* It probably should. The fix in `waitCatch` should have been extended to `link` too.
* I think `forkRepeat` is mostly paranoia (but I've learned that paranoia is usually good when dealing with exceptions). Perhaps with some `mask` we could get away without `forkRepeat`.
* I don't think an infinite loop is possible. `throwTo` will silently succeed if the target thread has died. It might receive an async exception, but that wouldn't lead to an infinite loop.
* wow, I'm honestly not sure. Want to try to construct a test case that behaves badly?

> FWIW, I'm increasingly unconvinced GHC's deadlock detection is correct... It fundamentally assumes that throwing an exception won't recover a thread, which isn't true.

I understand the problem, but I'm not sure you can reasonably do anything else. When there are N deadlocked threads, which one do you wake up? (the answer is not allowed to involve talking about which thread refers to which other thread, because that's unreasonably expensive to discover)

**Comment by ndmitchell** [comment]
I don't even use the `async` package at all, but am becoming increasingly convinced that is a bug in my code. Since I had some dead time, I thought I'd read the source to familiarise myself before converting some stuff to it. I agree that converting between sync and async exceptions sounds like a bad idea, deprecating `link` seems sensible.

> I understand the problem, but I'm not sure you can reasonably do anything else.

I'll have a think. I know what would work for the Shake specific case, but I'll see if it can generalise.

**Comment by simonmar** [comment]
I think this is done. I'm leaving `forkRepeat` in, even though it's probably just paranoia, because it's cheap and avoids delicate reasoning about what can throw exceptions.
