### ISSUE TITLE
Catching UserInterrupt inside threads

### ISSUE THREAD

**Issue by domenkozar** [simonmar/async#91]
I have the following use case:

Given a list of computations to be done, execute N at the time and if someone presses ctrl-c in the program, wait for those currently running to finish and cancel the rest.

I've tried using plain `mask_` inside `mapConcurrently`, but turns out AsyncCancelled exception is used within this package. It's currently not possible to mask it inside threads or distinguish by which [AsyncException](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#t:AsyncException) it was triggered.

What am I missing? :)

**Comment by simonmar** [comment]
Masking is not the right way to achieve what you want, because you'll also mask other kinds of exceptions which you probably do want to allow.

I would code up the policy exactly as you said it: keep track of the currently running threads, and wait for those to finish before cancelling the others. If you're doing the concurrency control via a semaphore then you can empty the semaphore before waiting, so that no more work is started while you're waiting for the active threads to finish.

**Comment by domenkozar** [comment]
That sounds good, thanks :)
